Aggregates queries
Ofarouq310/vet-clinic pull request #2
Opened 2023-05-25 23:36 UTC by Ofarouq310

## Summary of branch Implementations:

> - [x] New "species" column is added, and the schema file is modified.
> - [x] New animals' data is inserted.
> - [x] All required transaction updates have been implemented.
> - [x] Multiple queries and aggregates have been written to collect certain analyzed data.
> - [x] All implementations have been written using SQL.

-----

## Results of the transactions & queries:-

1.  Transaction which updates each animal with its corresponding species.
![Screenshot 2023-05-26 004129](https://github.com/Ofarouq310/vet-clinic/assets/102612396/7a9164b0-dcd2-481a-9cea-e0f416eaf472)

2. Transaction with rollback effect to see whether the records have been permanently deleted or not.
![Screenshot 2023-05-26 004337](https://github.com/Ofarouq310/vet-clinic/assets/102612396/698b6703-a847-4c86-ab2b-5ab21127c187)

3. Transaction which deletes one of the animals and adjusts the weight of the others from a negative number to a positive.
![Screenshot 2023-05-26 005225](https://github.com/Ofarouq310/vet-clinic/assets/102612396/daeb97f4-ba6c-4f65-b1fb-289056e456d1)

4. A query to answer the question of how many animals are there?
![Screenshot 2023-05-26 012229](https://github.com/Ofarouq310/vet-clinic/assets/102612396/67ee2dc0-084b-4423-be48-329d3c582d56)

5. A query to answer the question of how many animals have never tried to escape?
![Screenshot 2023-05-26 013912](https://github.com/Ofarouq310/vet-clinic/assets/102612396/f709047b-85be-4bb8-a03b-ecda1db140af)

6. A query to answer the question of what is the average weight of animals?
![Screenshot 2023-05-26 014342](https://github.com/Ofarouq310/vet-clinic/assets/102612396/f1a8df9b-9f4c-42b8-8008-8893de6edccc)

7. A query to answer the question of who escapes the most, neutered or not neutered animals?
![Screenshot 2023-05-26 014645](https://github.com/Ofarouq310/vet-clinic/assets/102612396/d6d840fb-0558-4b73-b6e7-d086be46b501)

8. A query to answer the question of what is the minimum and maximum weight of each type of animal?
![Screenshot 2023-05-26 014844](https://github.com/Ofarouq310/vet-clinic/assets/102612396/70057332-7e59-46ca-be45-9e445eac3e04)

9. What is the average number of escape attempts per animal type of those born between 1990 and 2000?
![Screenshot 2023-05-26 021050](https://github.com/Ofarouq310/vet-clinic/assets/102612396/50ef7f17-e1fb-4331-b31b-60befe7b83c5)

2023-05-25 23:58 UTC, addod19 requested changes
### Hi @Ofarouq310, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :+1: 
- [ ] README file is professional and has all relevant headers :fireworks: 
- [ ] Screenshot of the various queries are present in the PR :rocket: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 23:58 UTC, addod19 commented on schema.sql
> +    species VARCHAR(50)
- [ ] It would be better if we use the `Alter` command to add a new column to an existing table. For example; `ALTER TABLE animals ADD species varchar(255);`

2023-05-25 23:58 UTC, addod19 commented on queries.sql
> +SET species = 'unspecified';
- [ ] It would be better if we verify that the change was made after setting `species='unspecified'` as seen in the project requirements
![Screenshot from 2023-05-25 23-40-34](https://github.com/Ofarouq310/vet-clinic/assets/46388113/deac1cf7-7a66-4708-846f-c439ff5ff8ae)
To verify the change was made we run the command `SELECT species from animals;`

2023-05-25 23:58 UTC, addod19 commented on queries.sql
> +ROLLBACK;
- [ ] Also, after rolling back we verify if the change was undo by running that same command in the earlier comment

2023-05-25 23:58 UTC, addod19 commented on queries.sql
> +ROLLBACK;
- [ ] It would be better if verify if all the records in the Animals table exists after rolling back the transaction as we have in the project requirements
![Screenshot from 2023-05-25 23-50-01](https://github.com/Ofarouq310/vet-clinic/assets/46388113/7a7dae3a-3b79-442a-b172-2f47a7292dbe)

2023-05-25 23:58 UTC, addod19 commented on queries.sql
> +COMMIT;
- [ ] According to the project requirements, we should verify the change was made, then we commit after verifying. Now we also verify that change persist after commit as we have in the project requirements below
![Screenshot from 2023-05-25 23-44-30](https://github.com/Ofarouq310/vet-clinic/assets/46388113/4813e8bb-0d95-433c-ba83-dfa12b413e5d)

2023-05-26 07:28 UTC, Ofarouq310 commented on schema.sql
> +    species VARCHAR(50)
Pointes noted down, sir, thank you.

2023-05-26 07:29 UTC, Ofarouq310 commented on queries.sql
> +SET species = 'unspecified';
Points noted down, sir, thank you.

2023-05-26 07:29 UTC, Ofarouq310 commented on queries.sql
> +ROLLBACK;
Points noted down, sir, thank you.

2023-05-26 07:29 UTC, Ofarouq310 commented on queries.sql
> +ROLLBACK;
Points noted down, sir, thank you.

2023-05-26 07:29 UTC, Ofarouq310 commented on queries.sql
> +COMMIT;
Points noted down, sir, thank you.

2023-05-26 07:38 UTC, mikethreels requested changes
Hi Omar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- good job changing the queries as requested by the previous CR

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 07:38 UTC, mikethreels commented on schema.sql
> +    ALTER TABLE animals ADD species varchar(50);
- [ ] the `ALTER TABLE` command is used in the same way as the `CREATE TABLE` command, this means that it is to be used as a separate command not inside the `CREATE TABLE`

2023-05-26 07:51 UTC, Ofarouq310 commented on schema.sql
> +    ALTER TABLE animals ADD species varchar(50);
Thank you for drawing my attention to this, sir.

2023-05-26 07:51 UTC, Lizdev-05 approved these changes
Hi @Ofarouq310, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ]  Correct Git-flow followed 👍
- [ ]  README file is professional and has all relevant headers 🎆
- [ ]  Screenshots of the various queries are present in the PR 🚀
- [ ] Correct query implemented 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 07:54 UTC, merged

2023-06-07 13:11 UTC, cynthiainga reviewed
Hi @Ofarouq310, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Screenshots are implemented ✔️ 
- [ ] All queries are implemented correctly ✔️ 
- [ ] Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._